baseURL = "https://master.d3ug6kwsom8ec2.amplifyapp.com/"
languageCode = "ko-KR"
defaultContentLanguage = "ko"

title = "AWS Managed Blockchain 워크샵"
theme = "hugo-theme-learn"
themesdir = "."
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  description = "AWS IoT Services Workshop"
  author = "Yijeong Cho"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "aws"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages.ko]
title = "AWS Managed Blockchain 워크샵"
weight = 1
languageName = "한국어"

[[Languages.ko.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> 크레딧"
url = "/credits/"
weight = 30
